### ISSUE TITLE
Peer Review - Kyle Maitland

### ISSUE THREAD

**Issue by maitlandk90** [tjdombrowski/LegendSmith#7]
- [ ] Github page looks good, just make sure timelog and project plan are up to date

- [ ] JSPs looking simple for now, plenty of room for designing

- [ ] Code quality looking good. Working off a lot of data so just make sure things are lining up right

- [ ] Logging is there but could be used more

- [ ] Unit tests looking good!

- [ ] Tomcat authentication working right on start up

- [ ] Made mention that using api for only a small amount of data so maybe see if you can alter your api call to only get that data back

- [ ] Also mentioned jQuery UI wasn't working so if you still use it double check what you use.

Overall likes like your almost there, just a little left to go.

**Comment by pawaitemadisoncollege** [comment]
@maitlandk90 Which code quality tool from week 14 did you use and what were the findings?
